# Generated by Django 3.0.3 on 2020-06-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0004_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
    ]
