# Generated by Django 3.0.3 on 2020-06-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0005_remove_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Obrazovanie.Item'),
        ),
    ]
