# Generated by Django 3.0.3 on 2020-06-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0006_type_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='item',
        ),
    ]
