# Generated by Django 3.0.3 on 2020-06-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0009_auto_20200620_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='Item', to='Obrazovanie.Genre'),
        ),
    ]
