# Generated by Django 3.0.3 on 2020-06-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0011_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='genre',
        ),
    ]
