# Generated by Django 3.0.3 on 2020-06-20 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0015_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Obrazovanie.Format'),
        ),
    ]
