# Generated by Django 3.0.3 on 2020-06-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0018_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
