# Generated by Django 3.0.3 on 2020-07-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0027_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('CHECKING', 'CHECKING'), ('READY', 'READY')], default='Checking', max_length=120),
        ),
    ]
