# Generated by Django 3.0.3 on 2020-07-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0028_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='moderation',
            field=models.BooleanField(default=False),
        ),
    ]
