# Generated by Django 3.0.3 on 2020-07-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0029_report_moderation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
    ]
