# Generated by Django 3.0.3 on 2020-07-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0030_remove_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
