# Generated by Django 3.0.3 on 2020-07-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0031_auto_20200701_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
