# Generated by Django 3.0.3 on 2020-07-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0033_auto_20200701_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='clip',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
