# Generated by Django 3.0.3 on 2020-07-17 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Obrazovanie', '0045_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
