# Generated by Django 3.0.3 on 2020-07-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0046_report_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
