# Generated by Django 3.0.3 on 2020-09-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0048_report_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, upload_to='report-image'),
        ),
    ]
