# Generated by Django 3.0.3 on 2020-12-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Obrazovanie', '0049_auto_20200926_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='video',
        ),
        migrations.AddField(
            model_name='item',
            name='podcast',
            field=models.FileField(default='Please upload video', upload_to='item-podcast'),
        ),
    ]
