# Generated by Django 3.0.3 on 2020-07-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_auto_20200711_1943'),
        ('Dobro', '0005_auto_20200711_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dobro',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.Profile'),
        ),
    ]
