# Generated by Django 3.0.3 on 2020-07-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dobro', '0006_auto_20200711_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dobro',
            name='author',
        ),
    ]
