# Generated by Django 3.0.7 on 2020-06-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='garysh.jpg', upload_to='user-profile-image'),
        ),
    ]
