# Generated by Django 3.0.7 on 2020-06-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_userextended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtended',
        ),
    ]
