# Generated by Django 3.0.3 on 2020-06-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=120, null=True),
        ),
    ]
