# Generated by Django 3.0.3 on 2020-06-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_auto_20200612_1156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
