# Generated by Django 3.0.7 on 2020-06-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20200612_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='investment',
            field=models.IntegerField(null=True),
        ),
    ]
