# Generated by Django 3.0.7 on 2020-06-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_profile_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_investment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=90000),
        ),
    ]
