# Generated by Django 3.0.7 on 2020-06-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_remove_profile_total_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_investment',
            field=models.IntegerField(null=True),
        ),
    ]
