# Generated by Django 3.0.7 on 2020-06-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_profile_total_investment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_investment',
        ),
    ]
