# Generated by Django 3.0.3 on 2020-06-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_remove_profile_total_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
