# Generated by Django 3.0.3 on 2020-07-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_profile_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='investment',
        ),
    ]
