# Generated by Django 3.0.3 on 2020-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_auto_20200711_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='investment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_investment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=99999),
        ),
    ]
