# Generated by Django 3.0.3 on 2020-12-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_auto_20201226_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='garysh.jpg', upload_to='user-profile-image'),
        ),
    ]
