# Generated by Django 3.0.3 on 2020-12-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_auto_20201227_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='garysh.jpg', max_length=400, upload_to='user-profile-image'),
        ),
    ]
