# Generated by Django 3.0.3 on 2020-12-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_auto_20201227_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='garysh.jpg', upload_to='user-profile-image'),
        ),
    ]
