# Generated by Django 3.0.3 on 2020-12-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_auto_20201227_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='images',
        ),
    ]
