# Generated by Django 3.0.3 on 2020-12-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_auto_20201227_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.FileField(blank=True, default='garysh.jpg', upload_to='profile', verbose_name=' '),
        ),
    ]
