# Generated by Django 3.0.3 on 2020-12-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0033_auto_20201227_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_investment',
        ),
    ]
